mysite/accounts/urls.py
from django.urls import path
from . import views

app_name = "myaccounts"

urlpatterns = [
    path("login/", views.Login.as_view(), name="login"),
    path("logout/", views.Logout.as_view(), name="logout"),
    path("profile/", views.UserChangeView.as_view(), name="profile"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from app import views
from django.views.static import serve  # 追加

urlpatterns = [
    path("admin/", admin.site.urls),
    path("main/", views.main, name="main"),
    path("", include("accounts.urls")),
    path("signup/", views.SignUp.as_view(), name="signup"),
    path("search/", views.search, name="search"),
    # path("profile/", views.change_user_info, name="profile"),
    path("contact/", views.contact, name="contact"),
    path("contact_us/", views.contactUs, name="contact_us"),
    path("upload/", views.file_upload, name="upload"),
    path("ajax/", views.ajax, name="ajax"),
    path('favorite/',views.get_favorites,name='favorite'),
    path("oauth/", include("social_django.urls", namespace="social")),
    # path(r"^media/(?P<path>.*)$", serve, {"document_root": settings.MEDIA_ROOT}),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mysite/forms.py
from django.contrib.auth.forms import AuthenticationForm

class LoginFrm(AuthenticationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for filed in self.fileds.values():
            field.widget.attr['class']='form-control'
            field.widget.attr['placeholder']=field.label

mysite/mysite/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load sass_tags %}
<html>

<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width'>
    <title>FoodFriends</title>
    {% block style %}
    {% endblock %}
    <script src="https://kit.fontawesome.com/0aa33c3446.js" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <link rel="stylesheet" href="{% sass_src 'css/sass/styles.scss' %}" />
    <link rel='icon' type='image/png' href="{% static 'favicon.ico' %}">
    <script type='text/javascript' src=" {% static 'main/main.js' %}">
    </script>
</head>

<body>
    <div class='background'>
        <div class='background__column1'></div>
        <div class='background__column2'></div>
        <div class='background__column3'></div>
        <div class='background__column4'></div>
        <div class='background__column5'></div>
    </div>

    {% block base_content %}
    {% endblock %}

    <script>
        !(function () {
            const viewport = document.querySelector('meta[name="viewport"]');
            function switchViewport() {

                const value = window.outerWidth > 360
                    ? 'width=device-width,initial-scale=1'
                    : 'width=360';


                if (viewport.getAttribute('content') !== value) {
                    viewport.setAttribute('content', value);
                }
            }
            addEventListener('resize', switchViewport, false);
            switchViewport();
        })();
    </script>
</body>

</html>

mysite/mysite/templates/baseWithNav.html
{% extends 'base.html' %}
{% load static %}
{% block base_content %}
<div class='wrapper'>
    <nav class='nav'>
        <div class='nav__container'>
            <h1 class='nav__title'><a href="{% url 'main' %}"><i class="fas fa-utensils"></i> Foodies <i
                        class="fas fa-utensils"></i></a>
            </h1>
            <div class='nav__setting-container'>
                <button class='nav__setting-button'><i class='fa fa-bars'></i></button>
                <div class='nav__setting-window'>
                    <ul>
                        <li><a href="{% url 'myaccounts:profile' %}"><i class='far fa-user-circle'></i>プロフィール</a>
                        </li>
                        <li><a href="{% url 'contact' %}"><i class='fa fa-envelope'></i>お問い合わせ</a></li>
                        <li><a href="{% url 'myaccounts:login' %}">ログアウト</a></li>

                    </ul>
                </div>
            </div>
        </div>
    </nav>
    {% block content %}
    {% endblock %}

    <footer class='footer'>
        <div class='footer__container'>
            <div class='footer__about'>
                <p>松尾賢太</p>
                <p>〒132-0035 東京都江戸川区平井5-4-15</p>
            </div>
            <div class='footer__share'>
                <a class='fotter__facebook' href="http://www.facebook.com/share.php?u=https://www.google.com/"
                    rel="nofollow" target="_blank"><i class='fab fa-facebook-f'></i></a>
                <a class='fotter__twitter'
                    href="https://twitter.com/share?url=https://www.google.com/&text=Foodgram&hashtags=Foodgram"><i
                        class='fab fa-twitter' rel="nofollow" target="_blank"></i></a>

                <a class='footer__line'
                    href="https://timeline.line.me/social-plugin/share?url=https://www.google.com/"><img
                        src='/static/media/line.png' rel="nofollow" target="_blank"></a>

                <a class='fotter__pocket' href="http://getpocket.com/edit?url=https://www.google.com/&title=Foodgram"
                    rel="nofollow" rel="nofollow" target="_blank"><i class='fab fa-get-pocket'></i></a>
            </div>
            <div class='footer__contact'>
                <a href='{% url "contact" %}'><i class='fa fa-envelope'></i><span>お問い合わせ</span></a>
            </div>
            <div class='footer__copyright'>
                <p>Copyright (c) <a href='{% url "main" %}'>Foodgram</a>, Inc. All Rights Reserved.</p>
            </div>
        </div>
    </footer>
</div>
<script>
    $(document).on('click', function (e) {
        if (!$(e.target).closest('.nav__setting-button').length) {
            if (!$(e.target).closest('.nav__setting-window').length) {
                $(".nav__setting-window").hide()
            }
        }
    })
    $(function () {
        $(".nav__setting-button").click(function () {
            $(".nav__setting-window").toggle();
        });
    });
    $(".nav__search-form").submit(function (event) {
        // デフォルトの処理を中断
        event.preventDefault();
        console.log("aaa");
        var form = $(this);
        $.ajax({
            url: form.prop("action"),
            method: form.prop("method"),
            data: form.serialize(),
            timeout: 10000,
            dataType: "text",

            //リクエストが完了するまで実行される
            beforeSend: function () {
                $('.loading').removeClass('hide');
            },
            success: function (data) {
                $('.loading').addClass("is-hide");
            }
        })
            // 結果はdataに格納されて帰ってくる
            .done(function (datas) {
                search()
            })
    });
</script>

{% endblock %}

mysite/mysite/templates/contact.html
{% extends 'baseWithNav.html' %}
{% load static %}
{% load sass_tags %}
{% block style %}
<link rel='stylesheet' href="{% sass_src 'main/css/styles.scss' %}">
{% endblock %}
{% block content %}
<div class='contact'>
    <div class='contact__title'>
        <h2>お問い合わせフォーム (入力画面)</h2> <span class='contact__caution'>※ 内容に誤りがある場合はエラーが発生します</span>
    </div>

    <form class='contact__form' action='{% url "contact_us" %}' method="POST">
        {% csrf_token %}
        <div class='contact__table'>
            <div class='contact__tr'>
                <div class='contact__th'>
                    お名前<span class='contact__required'>必須</span>
                </div>
                <div class='contact__td'>
                    <input type='text' name='name' placeholder='お名前を入力してください'>
                </div>
            </div>
            <div class='contact__tr'>
                <div class='contact__th'>
                    タイトル<span class='contact__required'>必須</span>
                </div>
                <div class='contact__td'>
                    <select name='kind'>
                        <option value='お問い合わせ'>お問い合わせ</option>
                        <option value='ログインに関して'>ログインに関して</option>
                        <option value='お店のレビューに関して'>お店のレビューに関して</option>
                    </select>
                </div>
            </div>
            <div class='contact__tr'>
                <div class='contact__th'>
                    メールアドレス<span class='contact__required'>必須</span>
                </div>
                <div class='contact__td'>
                    <input type='text' name='email' placeholder='メールアドレスを入力してください'>
                    <input type='text' name='re-email' placeholder="確認のため再度入力してください">
                </div>
            </div>
            <div class='contact__tr'>
                <div class='contact__th'>
                    お問い合わせ内容<span class='contact__required'>必須</span>
                </div>
                <div class='contact__td'>
                    <textarea type='text' name='contents'></textarea>

                </div>
            </div>
        </div>
        <div class='contact__error is-hide'></div>
        <div class='contact__submit'>
            <button type='submit'>送 信</button>
        </div>
    </form>
</div>
<script>
    $('.contact__form').submit(function (event) {
        event.preventDefault();
        var form = $(this);
        $.ajax(
            {
                url: form.prop('action'),
                method: form.prop('method'),
                data: form.serialize(),
                timeout: 10000,
                dataType: 'text',
            }
        ).done(function (data) {
            if (data.includes('エラー')) {
                $('.contact__error').text(data).removeClass('is-hide');
            } else {
                window.location.href = data;
            }
        });
    })
</script>
{% endblock %}

mysite/mysite/templates/main.html
{% extends 'baseWithNav.html' %}
{% load static %}
{% load sass_tags %}
{% block style %}
<link rel="stylesheet" href="{% sass_src 'main/css/styles.scss' %}" />
{% endblock %}
{% block content %}
<div class='popup loading is-hide'>

</div>
<div class='success is-hide'>
</div>
<div class="dialog ">
    <div class='dialog__wrapper'>
        <div class='dialog__title'>
        </div>
        <div class='dialog__container'>
            <img class="dialog__image" alt="画像が見つかりません">
            <div class='dialog__comment-container'>
                <div class='dialog__friends'>
                    <div class='dialog__friend'>
                        <div class='dialog__friend-profile'>
                            <button class='dialog__friend-button' type='submit'><img class='dialog__friend-image'
                                    src='/static/media/profile/model1.png'></button>
                            <div class='dialog__friend-name'>namefdsafasd</div>
                        </div>
                        <div class='dialog__friend-comment'>
                            あfjdなsfb;えkwqlfbjくぇrklbfjけrlqbんjfk
                        </div>
                    </div>
                </div>
                <form class='dialog__form' action="{% url 'search' %}" method='POST'>
                    {% csrf_token %}
                    <textarea class='dialog__comment' name='comment' rows='4' cols='40'
                        placeholder='ここに感想を記入してください｡'></textarea>
                    <input class='dialog__input' name='good'>
                    <button class='dialog__submit' type='submit'>投稿する</button>
                </form>
            </div>
        </div>
    </div>
    <div class='dialog__close-button'>
        <i class='fa fa-close'></i>
    </div>
</div>
<ul>
    {% for place_id,person_num in results.items %}
    <script>
        window.addEventListener('load', function () {
            var place_id = "{{ place_id }}"
            var person_num = "{{ person_num }}"
            showPlace(place_id, parseFloat(person_num))
        });
    </script>
    {% endfor %}
</ul>

<div class='container'>
    <div class='friend'>
        {% for user in users %}
        <div class='friend__li'>
            <form class='friend__form' action='{% url "favorite" %}' method='POST'>
                {% csrf_token %}
                <input class='friend__input' name='user_button' value='{{ user.username }}'>
                <button class='friend__button' type='submit'>
                    <img class='friend__image' src='/media/{{ user.profile_image }}'
                        onerror="this.src='/static/media/default2.jpg'"></button>
                <p class='friend__name'>{{ user.username }} </p>
            </form>

        </div>
        {% endfor %}
    </div>
    <h2 class='content__title'>FoodMap</h2>
    <div class="map">

    </div>

    <div class='result'>
        <h2 class='result__title'>おすすめ</h2>
        <div class='result__list'>

        </div>
    </div>
    <div class='nav__search-container'>
        <form class='nav__search-form' action="/ajax/" method="POST">
            {% csrf_token %}
            <input class="nav__search-input" type='search' name='search' placeholder="&#xf002 検索">
    </div>
</div>

<!-- Async script executes immediately and must be after any DOM elements used in callback. -->
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBoEPpuwEmB_rxxltnl-WA6lRuFf9xYxBQ
    &callback=initMap&libraries=places&v=weekly" async></script>

<!-- ラベル付きマーカーを表示するライブラリ -->
<script src="https://unpkg.com/@googlemaps/markerwithlabel/dist/index.min.js"></script>
<script>
    $(document).on('click', function (e) {
        if (!$(e.target).closest('.dialog__container').length) {
            // ターゲット要素の外側をクリックした時の操作
            $(".dialog").hide()
            $('.dialog__comment').val('');
        }
    });
    $(function () {
        $(".dialog__form").submit(function (event) {
            console.log('ダイアログのajax処理を始めます')
            event.preventDefault();
            var form = $(this);
            $.ajax({
                url: form.prop('action'),
                method: form.prop('method'),
                data: form.serialize(),
                dataType: 'json',

                timeout: 10000,

                //リクエストが完了するまで実行される
                beforeSend: function () {
                    $('.loading').removeClass('is-hide');
                }
            })
                .done(function (data) {
                    console.log('done');
                    for (key in data) {
                        console.log(key)
                        var place_id = key;
                        var person_num = data[key];
                        showPlace(place_id, parseFloat(person_num));
                    }
                }).fail(function (data) {
                    alert('fail');
                }).always(function (data) {
                    console.log('always');
                    $('.loading').delay(2000).queue(function () {
                        console.log('delay');
                        $(this).addClass("is-hide").dequeue();
                        $('.success').removeClass('is-hide');
                        var timestamp = new Date().getTime();
                        var path = '/static/media/success.gif' + '?' + timestamp
                        path = 'url(' + path + ')'
                        $('.success').css('background-image', path);
                        // $('.success').fadeIn(200);
                        $('.success').delay(3000).queue(function () {
                            $('.success').addClass('is-hide').dequeue();
                            $('.dialog').hide();
                        });
                    });
                    $('.dialog__comment').val('');
                });
        });

        $('.friend__form').submit(function (event) {
            event.preventDefault();
            var form = $(this);
            $.ajax(
                {
                    url: form.prop('action'),
                    method: form.prop('method'),
                    data: form.serialize(),
                    dataType: 'json',
                    timeout: 10000,

                    beforeSend: function () {
                        $(".loading").removeClass('is-hide');
                    }
                }
            ).done(function (data) {
                saveResult(data);
                show();
            }).fail(function (data) {
                alert('fail')
            }).always(function (data) {
                console.log('always');
                $('.loading').delay(2000).queue(function () {
                    console.log('delay');
                    $(this).addClass("is-hide").dequeue();
                });
            });
        });
    });


</script>


{% endblock %}

mysite/mysite/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% block style %}
{% endblock %}
{% block base_content %}
<div class='login'>
    <div class='curtain'>
    </div>
    <div class='login__wrapper'>
        <div class='login__title left-to-right'>
            <h1>Foodgram</h1>
            <p>〜2020〜</p>
        </div>
        <div class='login__container down-to-top'>
            <h2>Foodgram</h2>
            <form action="" method="POST">
                {% csrf_token %}
                {% for field in form %}
                <div class="login__form-group">
                    {{ field }}
                </div>
                {% endfor %}

                {% for error in form.non_field_errors %}
                <div class="alert" role="alert">
                    <p>{{ error }}</p>
                </div>
                {% endfor %}
                <button type="submit" class="button">登録する</button>
            </form>
            <div class='login__register'>
                <a href="{% url 'myaccounts:login' %}">ログイン</a>
            </div>
        </div>

    </div>

</div>

<script>
    $('.curtain').fadeIn(2000);
    $('.down-to-top,.left-to-right').each(function () {
        var elemPos = $(this).offset().top;
        var scroll = $(window).scrollTop();
        var windowHeight = $(window).height();
        if (scroll > elemPos - windowHeight + 150) {
            $(this).delay(1000).queue(function () {
                $(this).addClass('scrollin');
            });
        }
    });

</script>
<!-- <script type="text/javascript" src="{% static 'main/jquery.textFx.js' %}"></script>
<script type="text/javascript" src="{% static 'main/jquery.transit.js' %}"></script> -->
{% endblock %}